### ISSUE TITLE
Texture painting problem

### ISSUE THREAD

**Issue by ThreeSRR** [zju3dv/NeuMesh#12]
Hi, thank you so much for such an awesome work. 

I am currently conducting experiments on texture painting. I am confused that I could not get the satisfying result like the dtu_scan105 with white glasses. Actually I only changed the white glasses in the painted image into yellow ones. 
Below is the painted image: 
![22fa853bd99f3a74f35561863ef8aa9](https://user-images.githubusercontent.com/62863808/220565238-c15011ce-e843-4103-9ba2-1bf5512050a6.png)
And here comes the painting result:
![00010000_0](https://user-images.githubusercontent.com/62863808/220565386-be5106dd-6fcb-4666-9297-c39abd8cdbe5.png)

Although all the parameters are the same as those in the white-glasses example, it seems that the image loss  failed to decrease adequately. I am wondering if there are any specific settings in texture painting, such as hyper-parameters.

**Comment by chobao** [comment]
In our experience, more training iteration will help the convergence of the model.

**Comment by chobao** [comment]
Close the inactive issue. Feel free to reopen it if you still have problems.
