### ISSUE TITLE
Link to Paper seems to be broken

### ISSUE THREAD

**Issue by daboe01** [zju3dv/NeuMesh#15]
http://www.cad.zju.edu.cn/home/gfzhang/papers/neumesh/neumesh.pdf does not work for me.

**Comment by chobao** [comment]
Hi, I think it may result from network. I can open it in my computer. Alternatively, you can read our paper in [arxiv](https://arxiv.org/abs/2207.11911) or in [ecva](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136760574.pdf)

**Comment by daboe01** [comment]
yes, you are right.
thank you!
