### ISSUE TITLE
The link for pre-trained models is expired

### ISSUE THREAD

**Issue by zychen-ustc** [zju3dv/NeuMesh#16]
The link for pre-trained models is expired. Could you kindly provide a new link for the pre-trained models? Thanks!

**Comment by chobao** [comment]
Sorry for the expired link! I have updated the link in README. Since the OneDrive shared link is only valid for 30 days, I will next look for another cloud service to store checkpoints.

**Comment by chobao** [comment]
Close the inactive issue. Feel free to reopen it if you still have problems.
