### ISSUE TITLE
Question for rendering

### ISSUE THREAD

**Issue by SCUTykLin** [zju3dv/NeuMesh#19]
U got the mesh of the objects, Why not just sample the points which near the mesh? like Tri-MipRF ICCV 23

**Comment by chobao** [comment]
Hi, in this paper, we focus more on editing so we don't pay much attention to improving the rendering quality. What you mention is a good measure to improve the efficiency and quality of rendering.

**Comment by chobao** [comment]
Close inactive issue but feel free to reopen it
