### ISSUE TITLE
ETA on training code

### ISSUE THREAD

**Issue by wamiq-reyaz** [zju3dv/NeuMesh#2]
Hiya,

Apologies for being too demanding, but do you have an estimated timeline for when the training code will be release?

Failing which, is there a way for me to contact you directly so that I can write a training script that matches yours (if the release is too far away).

Regards,

**Comment by ybbbbt** [comment]
Hi wamiq-reyaz,
I'm sorry that we are working on another project now, but we plan to release the refactored training code before the conference.

**Comment by wamiq-reyaz** [comment]
Thanks for the extremely quick response. Really appreciated.

I hope then you wouldn't mind me asking questions about the training script while I write my own?
That would be an immense help.

Best,
Wamiq

**Comment by chobao** [comment]
The full code has been released.
