### ISSUE TITLE
Question for the mesh

### ISSUE THREAD

**Issue by SCUTykLin** [zju3dv/NeuMesh#20]
Each vertex contains a sdf feature and texture feature. But the shape of the objects can be represented by mesh, why do we need the sdf feature?

Thx

**Comment by chobao** [comment]
The input mesh can be coarse (low-polygon), and not fully present the shape details.

Therefore, the sdf feature is needed to present the detailed shape information with the neural decoder and volume rendering techniques.

**Comment by chobao** [comment]
Close inactive issue but feel free to reopen it if you still have problems.
