### ISSUE TITLE
sample strategy

### ISSUE THREAD

**Issue by baoachun** [zju3dv/NeuMesh#22]
Hi, I have briefly reviewed the code and have a few questions I would like to clarify with you.

Is it reasonable to use KNN to find the 3DMM vertices adjacent to point for every sample point? Specifically, when a sample point is close to the camera but far from the object, or when a sample point is inside the mesh, could the nearest neighbor vertices found cause any anomalies?

<img width="768" alt="image" src="https://github.com/zju3dv/NeuMesh/assets/22114318/c544f815-c4b4-4380-bb2d-068970c92bf3">

**Comment by chobao** [comment]
Sorry for the late reply!
 I think KNN is ok but you need to introduce the signed distance at least because there is ambiguity at the points that have the same distance to the mesh surface but are inside and outside respectively.
