### ISSUE TITLE
Rendering time

### ISSUE THREAD

**Issue by wamiq-reyaz** [zju3dv/NeuMesh#4]
Hello,

I was wondering how much the render time is. I use your `render.py` script with the default params and it takes me about 24hrs to render the final video on an RTX 3090.

Is this the expected time? Or is the FRNN falling-back to a brute-force cpu-based method?
How exactly would I test if the FRNN library has been compiled properly?

There are a few tests inside the repo [here](https://github.com/lxxue/FRNN) but they are based on meshes and data that does no exist in the repo.

**Comment by chobao** [comment]
Hi, wamiq-reyaz! Rendering **a full-resolution(1600x1200) image** takes about 10 minutes on my RTX3090. The video in `README.md` is rendered with `--downscale 4`. I think the `downscale` option should be set  if a fast inference is needed:
https://github.com/zju3dv/NeuMesh/blob/86ebce817aeba64a00473e05d9d5ad413dbe4147/render.py#L295

**Comment by chobao** [comment]
Close the inactive activities. Feel free to reopen it if you still have problems.
