### ISSUE TITLE
Questions about Texture Painting. 

### ISSUE THREAD

**Issue by ZPDou98** [zju3dv/NeuMesh#6]
Hi there. Thanks for your great research work on NeRF editing. I am currently trying to implement the texture painting application according to the paper but got unsatisfying results. It seems that the optimization got stuck at a local minimum. Here are some results. 
Painted image:
![a](https://user-images.githubusercontent.com/73890185/188583091-6025f1e7-ec1e-4583-8dc6-d06267858aaa.png)

Selected vertices:
![a1](https://user-images.githubusercontent.com/73890185/188583188-38f6c4c7-c95e-4a4a-bfbb-f22422010e8a.png)

Optimization process(about 10000 steps):
![test1](https://user-images.githubusercontent.com/73890185/188583746-dcee7400-afe7-4869-929c-bc9d0c80672f.gif)

Are there any thoughts to improve it?

**Comment by ZPDou98** [comment]
Update: I stored the texture features on vertices as checkpoints and use them for novel view synthesis. Here is what I got:
![ezgif-3-0999aa9771](https://user-images.githubusercontent.com/73890185/188807133-3366dab0-ac85-476c-ac02-dd6a1c76df1c.gif)

Any suggestions for such a rendering result? Thanks in advance.

**Comment by jizongFox** [comment]
@ZPDou98  Hello. I happend to meet you here and I am extremely interested in text editing. I am wondering if I can ask you about details of the implementation?

**Comment by chobao** [comment]
The full code has been released.

**Comment by jizongFox** [comment]
@1612190130 Thanks for informing me. I just almost finished my own implementation. It is not too last to notice this.

**Comment by chobao** [comment]
Close the inactive issues. Feel free to reopen it if the problem still needs to be solved.
