### ISSUE TITLE
Coordinate frame and other questions

### ISSUE THREAD

**Issue by wamiq-reyaz** [zju3dv/NeuMesh#8]
Hiya,

You guys have released code that deals with the DTU dataset. Could you please clarify the global coordinate frame and the camera coordinates that the code expects?
This would be a great boon in training on our own datasets - especially the synthetic nerf dataset.

So the questions would be in the world coordinates is z-up?
In the camera coordinates, what are the coordinate ranges after perspective transform (-1 to 1, or 0 to 1). 
In the camera, is +z the forward direction or is it -z?

Other question are:
1. Why is there no `object_bounding_radius`? it is set for nuemesh, but the `get_neumesh_model` expects it under data?
2. Why do you set perturb to False?
3. What is white_background?

Hope you can answer.
Cheers,
Wamiq

**Comment by chobao** [comment]
Hi, wamiq-reyaz! The code dealing with DTU dataset is borrowed from [neurecon](https://github.com/ventusff/neurecon) and the processed DTU data is borrowed from [Neus](https://github.com/Totoro97/NeuS). You can refer to them for more details.

* As far as I know, the camera coordinate is an opencv camera model (i.e. right: x-axis, down: y-axis). 

* The backbone of our method is Neus, which expects that the object is within a unit sphere (i.e. `obj_bounding_radius`). Therefore the coordinate usually ranges from -1 to 1. 

* The white background is controlled by  `white_bkgd` in `volume_render`.

**Comment by chobao** [comment]
Close the inactive issues. Feel free to reopen it if the problem still needs to be solved.
